## Which authenticators (by logical name) and in what order
cache:
  ttlSeconds: 60
  cleanupAfterSeconds: 300
keyspaces:
  - name: ks1
    rolePrefix: "AP-MYKS-"
    roles:
      - name: READ
        resources:
          - type: data
            name: "*"
            permissions: [SELECT]
      - name: WRITE
        resources:
          - type: data
            name: "*"
            permissions: [MODIFY]
  - name: my_keyspace
    rolePrefix: "AP-MYKS-"
    roles:
      - name: "245c9adf-d0ef-4872-8955-b18a50a870bf"
        resources:
          - type: data
            name: "*"
            permissions: [ADMIN]
      - name: ADMIN #create this role AR
        resources:
          - type: data
            name: "*"
            permissions: [ALL]
defaultRoles:
  - name: READ
    resources:
      - type: data
        name: "*"
        permissions: [SELECT]
  - name: WRITE
    resources:
      - type: data
        name: "*"
        permissions: [MODIFY]
chained:
  authenticators: [jwt]
  authorizers:    [jwt]
externalServices:
  ldap:
    type: ldap
    url: ldap://ad.example.com:389
    bindUser: cn=admin,dc=example,dc=org
    bindPassword: secret
    userBaseDn: "ou=users,dc=example,dc=org"
    userAttribute: uid
    groupBaseDn: "ou=groups,dc=example,dc=org"
    groupAttribute: cn
    groupObjectClass: groupOfNames
    groupMemberAttribute: member
  jwt:
    jwksUrl: https://login.microsoftonline.com/e741d71c-c6b6-47b0-803c-0f3b32b07556/discovery/v2.0/keys
    issuer: https://sts.windows.net/e741d71c-c6b6-47b0-803c-0f3b32b07556/
    audience: api://836282d7-675d-40f0-997b-b3522d97a7ab
  corp_ldap:
    type: ldap
    # ...LDAP config for corporate directory...
  partner_ldap:
    type: ldap
    # ...LDAP config for partner directory...
  jwt_internal:
    type: jwt
    # ...JWT config for internal tokens...
  jwt_external:
    type: jwt
    # ...JWT config for external tokens...

# Per-logical-name plugin config
authenticators:
  jwt:
    class: com.att.cassandra.security.auth.jwt.JwtAuthenticator
    issuer: https://sts.windows.net/e741d71c-c6b6-47b0-803c-0f3b32b07556
    audience: https://management.core.windows.net/
    jwksUrl: https://login.microsoftonline.com/e741d71c-c6b6-47b0-803c-0f3b32b07556/discovery/v2.0/keys
    external_service: jwt
  internal:
    class: org.apache.cassandra.auth.PasswordAuthenticator
  ldap:
    class: com.att.cassandra.security.auth.ldap.LdapAuthenticator
    url: "ldap://localhost:389"
    bindUser: "cn=admin,dc=example,dc=org"
    bindPassword: "admin"
    userBaseDn: "ou=users,dc=example,dc=org"
    userAttribute: uid
    groupBaseDn: "ou=groups,dc=example,dc=org"
    groupAttribute: cn
    groupObjectClass: groupOfNames
    groupMemberAttribute: member
  internal:
    class: org.apache.cassandra.auth.PasswordAuthenticator
authorizers:
  jwt:
    class: com.att.cassandra.security.auth.jwt.JwtAuthorizer
    external_service: jwt
  cassandra:
    class: org.apache.cassandra.auth.CassandraAuthorizer
  ldap:
    class: com.att.cassandra.security.auth.ldap.LdapAuthorizer
